pipeline {
    agent { label 'testServer' }
// environment{
 //    DOCKER_HUB_CREDENTIALS = credentials('DOCKER_HUB_CRED')
  //   }
    stages {
        stage('checkout git branch') {
            steps {
git credentialsId: 'github', url: 'https://github.com/dharma0907/Edurakaproj2.git'
                     checkout scm
            }
        }
stage('docker build image') {
            // build docker image
            steps {
                sh "docker build --no-cache -t train-v${env.BUILD_NUMBER} -f trainapp/cicd/Dockerfile ."
            }
        }
        stage('docker tag the build') {
            steps {
               
                sh "docker tag train-v${env.BUILD_NUMBER} demo.goharbor.io/train/train:v${env.BUILD_NUMBER}"    
            }
        }
       stage('docker push image to harbor'){         
steps{
withCredentials([string(credentialsId: 'docker_pass', variable: 'docker')]) {
    // some block

             
              sh "docker login -u dharma006 -p $docker https://demo.goharbor.io"    
               sh "docker push demo.goharbor.io/train/train:v${env.BUILD_NUMBER}"
           }
      }
}
      stage('upade helm and run '){
        steps{
           sh "sudo /usr/local/bin/helm --kubeconfig /home/edureka/.kube/admin.conf  --install train harbor-qa/app-deploy --set image.tag='v${env.BUILD_NUMBER}' --namespace trainschdule -f cicd/charts"
         } 
      } 

}
}

